language: python 
python:
    - "3.6"
cache: pip 
# command to install dependencies
before_script:
 - easy_install distribute
 - pip install -r Activity1/requirements.txt 
# command to run tests 
script:
		- python Activity1/Activity1.py 

